#!/bin/bash

set -eu
set -o pipefail

bindir=$(realpath "$(dirname "$0")")

. "$bindir"/functions.bash

USAGE="Usage: $0"

HOST=95.211.13.68
USER=alleycatcc

mci
mcb cmd lftp
mcb  --rcfile lftp-rc
mcb  -f lftp-script
#mcb  -u "$USER"
#mcb  "$HOST"
mcg


