#!/bin/bash

set -eu
set -o pipefail

bindir=$(realpath "$(dirname "$0")")

. "$bindir"/functions.bash

USAGE="Usage: $0"

HOST=95.211.13.68
USER=alleycatcc

file1=index.html
file2=style.css

_ret0=

get-pass () {
    local ret="$1"
    local p
    info 'password?'
    read p
    read -d '' "$ret" <<< "$p" || true
}

get-pass _ret0
pass="$_ret0"

cmd ftp -invp "$HOST" <<EOT
quote USER "$USER"
quote PASS "$pass"
cd httpdocs
put $file1
put $file2
quit
EOT
